<?php $this->headStyle()->appendStyle('label { display: flex } label span { display: block; width: 100px } ') ?>

<h2>Ajouter un contact</h2>

<?= $this->form()->openTag($contactForm->setAttribute('novalidate', 'novalidate')) ?>
    <div>
        <?= $this->formLabel($contactForm->get('prenom')) ?>
        <?= $this->formElement($contactForm->get('prenom')) ?>
        <?= $this->formElementErrors($contactForm->get('prenom')) ?>
    </div>
    <?= $this->formRow($contactForm->get('nom')) ?>
    <?= $this->formRow($contactForm->get('email')) ?>
    <?= $this->formRow($contactForm->get('telephone')) ?>
    <?= $this->formRow($contactForm->get('societe')) ?>
    <button>Ajouter</button>
<?= $this->form()->closeTag() ?>