<?php /* @var $this \Zend\View\Renderer\PhpRenderer */ ?>
<?php /* @var $contacts \Application\Entity\Contact[] */ ?>
<?php $this->headTitle('Liste des contacts') ?>
<?php $this->headStyle()->appendStyle('body { background: beige; }'); ?>
<?php $this->placeholder('h2')->set('Liste des contacts') ?>

<table class="table">
    <?php foreach ($contacts as $c) : ?>
    <tr>
        <td><?= $c->getPrenom() ?> <?= $c->getNom() ?></td>
        <td>
            <a href="<?= $this->url('contacts/show', ['id' => $c->getId()]) ?>" class="btn btn-xs btn-primary">Afficher</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>

<a href="<?= $this->url('contacts/add') ?>">Ajouter un contact</a>