<?php $this->headTitle('Apple') ?>


<h2>Fiche société</h2>

<p>
    Nom : <?= $this->escapeHtml($societe->getNom()) ?>
</p>

<?php if ($societe->getAdresse()) : ?>
<p>
    Adresse : <?= $this->escapeHtml($societe->getAdresse()) ?>
</p>
<?php endif; ?>

<h3>Liste des contacts de cette société</h3>
<?php foreach ($societe->getContacts() as $c) : ?>
<p><?=$this->escapeHtml($c->getPrenom())?></p>
<?php endforeach; ?>
